INSERT INTO document_type (NAME)VALUES('CEDULA CIUDADANIA');
INSERT INTO document_type (NAME)VALUES('TARJETA IDENTIDAD');
INSERT INTO document_type (NAME)VALUES('PASAPORTE');
INSERT INTO document_type (NAME)VALUES('CEDULA EXTRANJERIA');